MyVehicleTracking.System/MyVehicleTrackingSystem.Wings/Controllers/DispatchController.cs
using Application.Client;
using Application.DispatchNote;
using Application.Driver;
using Application.Helper;
using Application.Vehicles;
using AutoMapper;
using Domain.Client;
using Domain.DispatchNote;
using Domain.Driver;
using Domain.Helper;
using Domain.Vehicles;
using MyVehicleTrackingSystem.Wings.Models;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyVehicleTrackingSystem.Wings.Controllers
{
    public class DispatchController : Controller
    {
        private readonly IDispatchNoteService _dispatchNoteService;
        private readonly IClientService _clientService;
        private readonly IDriverService _driverService;
        private readonly IHelperService _helperService;
        private readonly IVehicleService _vehicleService;

        public DispatchController(DispatchNoteService dispatchNoteService, ClientService clientService, DriverService driverService, HelperService helperService, VehicleService vehicleService)
        {
            if (dispatchNoteService == null)
            {
                throw new NullReferenceException("dispatchNoteService");
            }
            if (clientService == null)
            {
                throw new NullReferenceException("clientService");
            }
            if (driverService == null)
            {
                throw new NullReferenceException("driverService");
            }
            if (helperService == null)
            {
                throw new NullReferenceException("helperService");
            }
            if (vehicleService == null)
            {
                throw new NullReferenceException("vehicleService");
            }

            _dispatchNoteService = dispatchNoteService;
            _clientService = clientService;
            _driverService = driverService;
            _helperService = helperService;
            _vehicleService = vehicleService;
        }

        // GET: DispatchOpen
        [Authorize(Roles = "Business Owner, Dispatcher")]
        public ActionResult Open(string message, int? items)
        {
            if (message != null)
            {
                if (message.Equals("Success"))
                {
                    ModelState.AddModelError("", "Successfully deleted " + items + " dispatch(s)");
                }
                else
                {
                    ModelState.AddModelError("", "Please select Dispatch(s) to delete");
                }
            }

            IEnumerable<Domain.DispatchNote.DispatchNote> dispatchNotes = _dispatchNoteService.GetAllDispatchNote().Where(d => d.IsDeleted.Equals(false) && d.Status == "Open");
            IEnumerable<DispatchNoteViewModel> models = Mapper.Map<IEnumerable<DispatchNoteViewModel>>(dispatchNotes);
            return View(models);
        }

        //GET: DispatchClosed
        public ActionResult Closed()
        {
            IEnumerable<Domain.DispatchNote.DispatchNote> dispatchNotes = _dispatchNoteService.GetAllDispatchNote().Where(d => d.IsDeleted.Equals(false) && d.Status == "Closed");
            IEnumerable<DispatchNoteViewModel> models = Mapper.Map<IEnumerable<DispatchNoteViewModel>>(dispatchNotes);
            return View(models);
        }

        //Get: DispatchCancelled
        public ActionResult Cancelled()
        {
            IEnumerable<Domain.DispatchNote.DispatchNote> dispatchNotes = _dispatchNoteService.GetAllDispatchNote().Where(d => d.IsDeleted.Equals(false) && d.Status == "Cancelled");
            IEnumerable<DispatchNoteViewModel> models = Mapper.Map<IEnumerable<DispatchNoteViewModel>>(dispatchNotes);
            return View(models);
        }

        // GET: Dispatch/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        //GET: Dispatch ClosedCancelledView
        [HttpGet]
        public ActionResult ClosedCancelledView(int id)
        {
            try
            {
                Domain.DispatchNote.DispatchNote dispatch = _dispatchNoteService.GetDispatchNoteById(id);
                DispatchNoteViewModel model = Mapper.Map<DispatchNoteViewModel>(dispatch);
                model.QuantityType = CustomDataHelper.DataHelper.GetQuentity();
                model.Client_OperationType = GetClients();
                model.DriverName_Grade = GetDrivers();
                model.HelperName = GetHelpers();
                model.VehiclePlateNumber = GetVehicles();
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        //POST: Dispatch/ClosedCancelledView
        [HttpPost]
        public ActionResult ClosedCancelledView()
        {
            return View();
        }

        // GET: Dispatch/ViewDispatch
        [HttpGet]
        public ActionResult ViewDispatch(int id)
        {
            try
            {
                Domain.DispatchNote.DispatchNote dispatch = _dispatchNoteService.GetDispatchNoteById(id);
                DispatchNoteViewModel model = Mapper.Map<DispatchNoteViewModel>(dispatch);
                model.QuantityType = CustomDataHelper.DataHelper.GetQuentity();
                model.Client_OperationType = GetClients();
                model.DriverName_Grade = GetDrivers();
                model.HelperName = GetHelpers();
                model.VehiclePlateNumber = GetVehicles();
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // POST: Dispatch/ViewDispatch
        [HttpPost]
        public ActionResult ViewDispatch(DispatchNoteViewModel model, string button)
        {
            try
            {
                DispatchNote dispatchNote = Mapper.Map<DispatchNote>(model);

                if (button.Equals("Close"))
                {
                    dispatchNote.Status = "Closed";
                }
                else
                {
                    dispatchNote.IsDispatchNoteReceived = false;
                    dispatchNote.IsGoodsDelivered = false;
                    dispatchNote.Remarks = null;
                    dispatchNote.Status = "Cancelled";
                }

                _dispatchNoteService.UpdateDispatchNoteStatus(dispatchNote);
                ModelState.Clear();
                ViewData["Success"] = "Successfully Updated.";
                return RedirectToAction("Open");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Dispatch/Create
        public ActionResult Create()
        {
            DispatchNoteViewModel model = new DispatchNoteViewModel();
            model.QuantityType = CustomDataHelper.DataHelper.GetQuentity();
            model.Client_OperationType = GetClients();
            model.DriverName_Grade = GetDrivers();
            model.HelperName = GetHelpers();
            model.VehiclePlateNumber = GetVehicles();
            return View(model);
        }

        // POST: Dispatch/Create
        [HttpPost]
        public ActionResult Create(DispatchNoteViewModel model, string button)
        {
            try
            {
                DispatchNote dispatchNote = Mapper.Map<DispatchNote>(model);
                dispatchNote.DispatchId = GenarateDispatchNumber();
                dispatchNote.Status = "Open";

                if (button.Equals("Print"))
                {
                    dispatchNote.IsPrinted = true;
                }

                Client clienFromDb = _clientService.GetClientById(Convert.ToInt32(model.Client));

                dispatchNote.Client = clienFromDb.CompanyName + " - " + clienFromDb.OperationType;
                dispatchNote.VehicleLicensePlateNumber = _vehicleService.GetVehicleDetailById(Convert.ToInt32(model.VehicleLicensePlateNumber)).VehicleNumber;

                _dispatchNoteService.SaveDispatchNote(dispatchNote);
                ModelState.Clear();
                ViewData["Success"] = "Successfully Added.";
                return RedirectToAction("Open");
            }
            catch (Exception e)
            {
                return View();
            }
        }

        // GET: Dispatch/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                Domain.DispatchNote.DispatchNote dispatch = _dispatchNoteService.GetDispatchNoteById(id);
                DispatchNoteViewModel model = Mapper.Map<DispatchNoteViewModel>(dispatch);
                model.Client = GetClients().Where(c => c.Text == model.Client).Select(c => c.Value).FirstOrDefault();
                model.QuantityType = CustomDataHelper.DataHelper.GetQuentity();
                model.Client_OperationType = GetClients();
                model.DriverName_Grade = GetDrivers();
                model.HelperName = GetHelpers();
                model.VehiclePlateNumber = GetVehicles();
                model.VehicleLicensePlateNumber = GetVehicles().Where(v => v.Text == model.VehicleLicensePlateNumber).Select(c => c.Value).FirstOrDefault();
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // POST: Dispatch/Edit/5
        [HttpPost]
        public ActionResult Edit(DispatchNoteViewModel model, string button)
        {
            try
            {
                DispatchNote dispatchNote = Mapper.Map<DispatchNote>(model);
                dispatchNote.Status = "Open";

                if (button.Equals("Print"))
                {
                    dispatchNote.IsPrinted = true;
                }

                Client clienFromDb = _clientService.GetClientById(Convert.ToInt32(model.Client));

                dispatchNote.Client = clienFromDb.CompanyName + " - " + clienFromDb.OperationType;

MyVehicleTracking.System/MyVehicleTrackingSystem.Wings/Views/Dispatch/Cancelled.cshtml
@model IEnumerable<MyVehicleTrackingSystem.Wings.Models.DispatchNoteViewModel>

@{
    ViewBag.Title = "Cancelled";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .nav-tabs > li > a {
        color: #000 !important;
    }

        .nav-tabs > li > a:hover {
            color: rgba(0,0,0,0.2) !important;
        }
</style>

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation"> <a href='@Url.Action("Open", "Dispatch")' title="Open">Open</a></li>
    <li role="presentation"><a href='@Url.Action("Closed", "Dispatch")' title="Closed">Closed</a></li>
    <li role="presentation" class="active"><a href='@Url.Action("Cancelled", "Dispatch")' title="Cancelled">Cancelled</a></li>
</ul>

<div class="row">
    <div class="col-md-12">
        <div class="well margin-top-20 create-forms">
            <div class="col-md-12 marginBottom tableTitle row remove-margin form-heading">
                @*<div class="form-icon light-blue col-xs-1"><i class="fa fa-user-plus"></i></div>*@
                <div class="text-light-blue col-xs-12">Cancelled Dispatch</div>
            </div>
            <div class="form-horizontal">
                <fieldset class="scheduler-border">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="tbtr">
                                <th>
                                    @Html.DisplayNameFor(model => model.DispatchId)
                                </th>
                                <th>
                                    @Html.DisplayName("Client - Operation Type")
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CompanyAddress)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Driver)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.VehicleLicensePlateNumber)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DispatchDate)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DispatchId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Client)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyAddress)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Driver)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.VehicleLicensePlateNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DispatchDate)
                                    </td>
                                    <td>
                                        @Html.ActionLink("View", "ClosedCancelledView", new { id = item.DispatchNoteId }, new { @class = "viewbtn btn btn-default btn-raised" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <p>
                        @Html.ActionLink("Back", "Index", "Home", null, new { @class = "btn btn-info btn-raised" })
                    </p>
                </fieldset>
            </div>
        </div>

    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/paginathing.js"></script>
    <script>
        //Add pagination fuctionality
        jQuery(document).ready(function ($) {
            for (var i = 1; i <= 500; i++) {
                $('.list-group').append('<li class="list-group-item"> Item ' + i + '</li>');
            }

            $('.table tbody').paginathing({
                limitPagination: false,
                perPage: 10,
                insertAfter: '.table',
                containerClass: 'panel-footer'
            });
        });
    </script>
}

MyVehicleTracking.System/MyVehicleTrackingSystem.Wings/Views/Dispatch/Closed.cshtml
@model IEnumerable<MyVehicleTrackingSystem.Wings.Models.DispatchNoteViewModel>

@{
    ViewBag.Title = "Closed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .nav-tabs > li > a {
        color: #000 !important;
    }

        .nav-tabs > li > a:hover {
            color: rgba(0,0,0,0.2) !important;
        }
</style>

<ul class="nav nav-tabs" role="tablist">
    @if (!User.IsInRole("Accounting Staff"))
    {
        <li role="presentation"> <a href='@Url.Action("Open", "Dispatch")' title="Open">Open</a></li>
    }
    <li role="presentation" class="active"><a href='@Url.Action("Closed", "Dispatch")' title="Closed">Closed</a></li>
    <li role="presentation" class=""><a href='@Url.Action("Cancelled", "Dispatch")' title="Cancelled">Cancelled</a></li>
</ul>

<div class="row">
    <div class="col-md-12">
        <div class="well margin-top-20 create-forms">
            <div class="col-md-12 marginBottom tableTitle row remove-margin form-heading">
                @*<div class="form-icon light-blue col-xs-1"><i class="fa fa-user-plus"></i></div>*@
                <div class="text-light-blue col-xs-12">Closed Dispatch</div>
            </div>
            <div class="form-horizontal">
                <fieldset class="scheduler-border">
                    <table class="table table-bordered">
                        <thead>
                            <tr class="tbtr">
                                @if (User.IsInRole("Accounting Staff"))
                                {
                                    <th>
                                        <input type="checkbox" name="checkbox1" id="checkAll" />
                                        <label for="checkbox1"></label>
                                    </th>
                                }
                                <th>
                                    @Html.DisplayNameFor(model => model.DispatchId)
                                </th>
                                <th>
                                    @Html.DisplayName("Client - Operation Type")
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CompanyAddress)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Driver)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.VehicleLicensePlateNumber)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DispatchDate)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    @if (User.IsInRole("Accounting Staff"))
                                    {
                                        <td>
                                            <input type="checkbox" name="dispatchNoteToSelect" id="dispatchNoteToSelect" value="@item.DispatchNoteId" />
                                        </td>
                                    }
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DispatchId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Client)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CompanyAddress)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Quantity)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Driver)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.VehicleLicensePlateNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DispatchDate)
                                    </td>
                                    <td>
                                        @Html.ActionLink("View", "ClosedCancelledView", new { id = item.DispatchNoteId }, new { @class = "viewbtn btn btn-default btn-raised" })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <p>
                        @Html.ActionLink("Back", "Index", "Home", null, new { @class = "btn btn-info btn-raised" })
                    </p>
                </fieldset>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/paginathing.js"></script>
    <script>
        $(function () {
            $("#checkAll").click(function () {
                if ($("#checkAll").is(':checked')) {
                    $("input[type=checkbox]").each(function () {
                        $(this).prop("checked", true);
                    });

                } else {
                    $("input[type=checkbox]").each(function () {
                        $(this).prop("checked", false);
                    });
                }
            });
        });

        // Uncheck All Checkboxes
        function uncheckAll() {
            $("input[type='checkbox']:checked").prop("checked", false)
        }
        $('#clearcheckbox').on('click', uncheckAll)

        //Add pagination fuctionality
        jQuery(document).ready(function ($) {
            for (var i = 1; i <= 500; i++) {
                $('.list-group').append('<li class="list-group-item"> Item ' + i + '</li>');
            }

            $('.table tbody').paginathing({
                limitPagination: false,
                perPage: 10,
                insertAfter: '.table',
                containerClass: 'panel-footer'
            });
        });
    </script>
}

MyVehicleTracking.System/MyVehicleTrackingSystem.Wings/Views/Dispatch/Open.cshtml
@model IEnumerable<MyVehicleTrackingSystem.Wings.Models.DispatchNoteViewModel>

@{
    ViewBag.Title = "Open";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .nav-tabs > li > a {
        color: #000 !important;
    }

        .nav-tabs > li > a:hover {
            color: rgba(0,0,0,0.2) !important;
        }
</style>
@*<div class="icon-nav lg-only">
        <a href='@Url.Action("Cancelled", "Dispatch")' title="Cancelled" class="right active"><span class="active" value="">Cancelled</span></a>
        <a href='@Url.Action("Closed", "Dispatch")' title="Closed" class="middle"><span class="" value="">Closed</span></a>
        <a href='@Url.Action("Open", "Dispatch")' title="Open" class="left"><span class="right">Open</span></a><br>
    </div>*@

<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"> <a href='@Url.Action("Open", "Dispatch")' title="Open">Open</a></li>
    <li role="presentation"><a href='@Url.Action("Closed", "Dispatch")' title="Closed">Closed</a></li>
    <li role="presentation" class=""><a href='@Url.Action("Cancelled", "Dispatch")' title="Cancelled">Cancelled</a></li>
</ul>

@*<ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
    <li><a data-toggle="tab" href="#menu1">Menu 1</a></li>
    <li><a data-toggle="tab" href="#menu2">Menu 2</a></li>
    <li><a data-toggle="tab" href="#menu3">Menu 3</a></li>
</ul>*@

<div class="row">
    <div class="col-md-12">
        <div class="well margin-top-20 create-forms">
            <div class="col-md-12 marginBottom tableTitle row remove-margin form-heading">
                @*<div class="form-icon light-blue col-xs-1"><i class="fa fa-user-plus"></i></div>*@
                <div class="text-light-blue col-xs-12">Open Dispatch</div>
            </div>
            <div class="form-horizontal">
                <fieldset class="scheduler-border">
                    <div class="col-md-12">
                        <div class="col-md-5">
                            <p>
                                @Html.ActionLink("Create New", "Create", null, null, new { @class = "btn btn-info btn-raised" })
                            </p>
                        </div>
                        @using (Html.BeginForm("Search", "Dispatch"))
                        {
                            <div class="col-md-2">
                                <div class="input-group date" data-provide="datepicker">
                                    <div class="input-group-addon">
                                        <span>From</span>
                                    </div>
                                    <input type="text" name="From" class="form-control">
                                    <div class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-2">
                                <div class="input-group date" data-provide="datepicker">
                                    <div class="input-group-addon">
                                        <span>To</span>
                                    </div>
                                    <input type="text" name="To" class="form-control">
                                    <div class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-3">
                                <Sdiv class="input-group add-on">
                                    <input class="form-control" placeholder="Search" name="Term" id="srch-term" type="text">
                                    <div class="input-group-btn">
                                        <button class="searchbtn btn btn-default btn-raised" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                    </div>
                                </Sdiv>
                            </div>
                        }
                    </div>
                    <table class="table table-bordered">
                        <thead>
                            <tr class="tbtr">
                                <th>
                                    @Html.DisplayNameFor(model => model.DispatchId)
                                </th>
                                <th>
                                    @Html.DisplayName("Client - Operation Type")
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.CompanyAddress)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Quantity)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Driver)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.VehicleLicensePlateNumber)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.DispatchDate)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count() > 0)
                            {
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DispatchId)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Client)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.CompanyAddress)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Quantity)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Driver)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.VehicleLicensePlateNumber)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.DispatchDate)
                                        </td>
                                        <td>
                                            @if (item.IsPrinted)
                                            {
                                                @Html.ActionLink("View", "ViewDispatch", new { id = item.DispatchNoteId }, new { @class = "viewbtn btn btn-default btn-raised" })
                                            }
                                            else
                                            {
                                                @Html.ActionLink("Edit", "Edit", new { id = item.DispatchNoteId }, new { @class = "editbtn btn btn-default btn-raised" })
                                            }
                                            <br>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="8" align="center" style="color:red">No open dispatch notes available.</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <p>
                        @Html.ActionLink("Back", "Index", "Home", null, new { @class = "btn btn-info btn-raised" })
                    </p>
                </fieldset>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/paginathing.js"></script>
    <script>
        //Add pagination fuctionality
        jQuery(document).ready(function ($) {
            for (var i = 1; i <= 500; i++) {
                $('.list-group').append('<li class="list-group-item"> Item ' + i + '</li>');
            }

            $('.table tbody').paginathing({
                limitPagination: false,
                perPage: 10,
                insertAfter: '.table',
                containerClass: 'panel-footer'
            });
        });
    </script>
}